// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Migrations precisam de conexão DIRETA (porta 5432).
    // O pooler do Supabase (6543) não suporta DDL/advisory locks.
    url: process.env["DIRECT_URL"],
  },
});
